INSERT INTO `competition`.`teammember` (`first_name`, `tussenvoegsel`, `last_name`, `phone_number`, `email`) VALUES ('Luc', null, 'Bosch', null, null);
INSERT INTO `competition`.`teammember` (`first_name`, `tussenvoegsel`, `last_name`, `phone_number`, `email`) VALUES ('Ahmet', null, 'Ersahin', null, null);
INSERT INTO `competition`.`teammember` (`first_name`, `tussenvoegsel`, `last_name`, `phone_number`, `email`) VALUES ('Gaico', null, 'Stoltenborgh', null, null);
INSERT INTO `competition`.`teammember` (`first_name`, `tussenvoegsel`, `last_name`, `phone_number`, `email`) VALUES ('Satish', null, 'Biharie', null, null);
INSERT INTO `competition`.`teammember` (`first_name`, `tussenvoegsel`, `last_name`, `phone_number`, `email`) VALUES ('Bastiaan', null, 'Karelse', null, null);
INSERT INTO `competition`.`teammember` (`first_name`, `tussenvoegsel`, `last_name`, `phone_number`, `email`) VALUES ('Wiebe', null, 'Hoekstra', null, null);

INSERT INTO `competition`.`team` (`teamname`) VALUES ('Siebel Giants');
INSERT INTO `competition`.`team_teammember` (`team_id`, `team_member_id`) VALUES (1, 1);
INSERT INTO `competition`.`team_teammember` (`team_id`, `team_member_id`) VALUES (1, 2);
INSERT INTO `competition`.`team` (`teamname`) VALUES ('Muppets 1');
INSERT INTO `competition`.`team_teammember` (`team_id`, `team_member_id`) VALUES (2, 3);
INSERT INTO `competition`.`team_teammember` (`team_id`, `team_member_id`) VALUES (2, 4);
INSERT INTO `competition`.`team` (`teamname`) VALUES ('Digital Masters');
INSERT INTO `competition`.`team_teammember` (`team_id`, `team_member_id`) VALUES (3, 5);
INSERT INTO `competition`.`team_teammember` (`team_id`, `team_member_id`) VALUES (3, 6);

INSERT INTO `competition`.`matches` (`home_goals`, `away_goals`) VALUES (null, null);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (1, 1);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (1, 2);
INSERT INTO `competition`.`matches` (`home_goals`, `away_goals`) VALUES (null, null);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (2, 1);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (2, 3);
INSERT INTO `competition`.`matches` (`home_goals`, `away_goals`) VALUES (null, null);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (3, 2);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (3, 1);
INSERT INTO `competition`.`matches` (`home_goals`, `away_goals`) VALUES (null, null);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (4, 2);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (4, 3);
INSERT INTO `competition`.`matches` (`home_goals`, `away_goals`) VALUES (null, null);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (5, 3);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (5, 1);
INSERT INTO `competition`.`matches` (`home_goals`, `away_goals`) VALUES (null, null);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (6, 3);
INSERT INTO `competition`.`match_team` (`match_id`, `team_id`) VALUES (6, 2);
